### ISSUE TITLE
Plugin not working in rhythmbox 3.0.2: ImportError: No module named 'rb'

### ISSUE THREAD

**Issue by Johann-Tree** [fossfreedom/remember-the-rhythm#1]
I installed the plugin, selected it to use and now I get the following messages when I start rhythmbox in terminal:

```
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/remember-the-rhythm/remember-the-rhythm.py", line 13, in <module>
    import rb
ImportError: No module named 'rb'

(rhythmbox:25964): libpeas-WARNING **: Error loading plugin 'remember-the-rhythm'
```

I'm running rhythmbox 3.0.2 on Ubuntu 14.04.3 LTS 64bit.
What other information can I provide helping to solve that problem?
Thank you.

**Comment by fossfreedom** [comment]
OK the above commit should resolve this.  Thanks for the report

**Comment by Johann-Tree** [comment]
No, I still get the same error.

**Comment by fossfreedom** [comment]
Check that the .plugin file in /use/lib/rhythmbox/plugins/remember-the-rhythm contains the Depends=rb line as per the commit

**Comment by Johann-Tree** [comment]
I'm sorry, I don't know what was going wrong. I had downloaded the new zip and extracted and installed. But the file remember-the-rhythm.plugin did'nt contain that line…
Now it is working.
Thank you very much!
