### ISSUE TITLE
Preferences does not work

### ISSUE THREAD

**Issue by Johann-Tree** [fossfreedom/remember-the-rhythm#2]
When clicking on the preferences button this plugin selected, nothing happens but I get following errors on terminal:
```Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/remember-the-rhythm/remember-the-rhythm.py", line 213, in do_create_configure_widget
    'ui/remember_preferences.ui'))
TypeError: Argument 1 does not allow None as a value

(rhythmbox:27431): libpeas-CRITICAL **: show_configure_cb: assertion 'GTK_IS_WIDGET (conf_widget)' failed

```

I'm using rhythmbox 3.0.2 on Ubuntu 14.04.3 LTS 64bit.
```

**Comment by fossfreedom** [comment]
apologies for that.  Should be now resolved.

When you've downloaded and installed again there should be a .ui file is /usr/share/rhythmbox/plugins/remember-the-rhythm/ui

**Comment by Johann-Tree** [comment]
Thanks a lot, it's working like a charm!
