### ISSUE TITLE
Repository info incorrect

### ISSUE THREAD

**Issue by SimonDedman** [fossfreedom/remember-the-rhythm#9]
On the github front page, Installation, Ubuntu Repository:

> sudo add-apt-repository ppa:fossfreedom/rhythmbox-plugins sudo apt-get update sudo apt-get install rhythmbox-plugin-remember-the-rhythm

Should be:

> sudo add-apt-repository ppa:fossfreedom/rhythmbox-plugins sudo apt update sudo apt install rhythmbox-plugin-remembertherhythm

That's all. Thanks!

**Comment by fossfreedom** [comment]
https://github.com/fossfreedom/remember-the-rhythm/commit/8c54b52423a0ae333e510ecd39e1e02101b42ee4
